//! Tray icon and menu. This layer does exactly two things: build the menu, and
//! push `AppState` onto the UI unconditionally. **Every decision lives in
//! `state.rs`; nothing here chooses anything.**

use std::error::Error;
use std::time::Instant;

use tray_icon::menu::{CheckMenuItem, IsMenuItem, Menu, MenuItem, PredefinedMenuItem, Submenu};
use tray_icon::{Icon, TrayIcon, TrayIconBuilder};

use crate::i18n::Strings;
use crate::state::{AppState, SPANS, Span};

pub const ID_SYSTEM: &str = "system";
pub const ID_DISPLAY: &str = "display";
pub const ID_REMAIN: &str = "remain";
pub const ID_QUIT: &str = "quit";

/// Duration entries use ids `span0`, `span1`, and so on, where the number is an
/// index into [`SPANS`]. A prefix plus an index avoids maintaining one constant
/// per duration: adding or removing options means touching only `SPANS`.
pub const ID_SPAN_PREFIX: &str = "span";

/// build.rs compiles assets/active.ico as resource id 1 and idle.ico as id 2.
const ICON_ACTIVE: u16 = 1;
const ICON_IDLE: u16 = 2;

pub struct Ui {
    tray: TrayIcon,
    strings: &'static Strings,
    system: CheckMenuItem,
    display: CheckMenuItem,
    /// The duration radio group. muda has no native radio item, so mutual
    /// exclusion is maintained by hand: each sync checks exactly the one that
    /// matches the current span.
    spans: Vec<(CheckMenuItem, Span)>,
    remaining: MenuItem,
    icon_active: Icon,
    icon_idle: Icon,
    /// The menu has to stay alive, or right-clicking the tray pops up nothing.
    _menu: Menu,
    _span_menu: Submenu,
}

impl Ui {
    pub fn build(strings: &'static Strings) -> Result<Ui, Box<dyn Error>> {
        let icon_active = Icon::from_resource(ICON_ACTIVE, None)?;
        let icon_idle = Icon::from_resource(ICON_IDLE, None)?;

        let system = CheckMenuItem::with_id(ID_SYSTEM, strings.keep_system, true, false, None);
        let display = CheckMenuItem::with_id(ID_DISPLAY, strings.keep_screen, true, false, None);

        // Duration entries are generated by zipping SPANS with the labels for
        // the active language; the index becomes the id suffix.
        let span_items: Vec<(CheckMenuItem, Span)> = SPANS
            .iter()
            .zip(strings.spans.iter())
            .enumerate()
            .map(|(i, (span, label))| {
                let item = CheckMenuItem::with_id(
                    format!("{ID_SPAN_PREFIX}{i}"),
                    label,
                    true,
                    *span == Span::Forever, // start out on "Indefinitely"
                    None,
                );
                (item, *span)
            })
            .collect();
        let span_refs: Vec<&dyn IsMenuItem> = span_items
            .iter()
            .map(|(item, _)| item as &dyn IsMenuItem)
            .collect();
        let span_menu = Submenu::with_items(strings.duration, true, &span_refs)?;

        // The "remaining" row is display only and never clickable.
        let remaining = MenuItem::with_id(ID_REMAIN, strings.no_timer, false, None);
        let quit = MenuItem::with_id(ID_QUIT, strings.exit, true, None);

        let menu = Menu::with_items(&[
            &system,
            &display,
            &PredefinedMenuItem::separator(),
            &span_menu,
            &PredefinedMenuItem::separator(),
            &remaining,
            &PredefinedMenuItem::separator(),
            &quit,
        ])?;

        let tray = TrayIconBuilder::new()
            .with_menu(Box::new(menu.clone()))
            .with_icon(icon_idle.clone())
            .with_tooltip((strings.tooltip)(strings.tip_off, None))
            .with_menu_on_left_click(true)
            .build()?;

        Ok(Ui {
            tray,
            strings,
            system,
            display,
            spans: span_items,
            remaining,
            icon_active,
            icon_idle,
            _menu: menu,
            _span_menu: span_menu,
        })
    }

    /// Push the state onto the UI. This is the **only** path that updates the
    /// UI: every change to `AppState` must be followed by a call here, and no
    /// other code is allowed to touch menu items directly.
    pub fn sync(&self, state: &AppState, now: Instant, power_ok: bool) {
        self.system.set_checked(state.system());
        self.display.set_checked(state.display());

        for (item, span) in &self.spans {
            item.set_checked(*span == state.span());
        }

        self.remaining
            .set_text(state.remaining_text(now, self.strings));

        let icon = if state.is_active() && power_ok {
            self.icon_active.clone()
        } else {
            self.icon_idle.clone()
        };
        let _ = self.tray.set_icon(Some(icon));

        let tip = if power_ok {
            state.tooltip(now, self.strings)
        } else {
            self.strings.tip_power_failed.to_string()
        };
        let _ = self.tray.set_tooltip(Some(tip));
    }
}
