//! Tray icon and menu. This layer does exactly two things: build the menu, and
//! push `AppState` onto the UI unconditionally. **Every decision lives in
//! `state.rs`; nothing here chooses anything.**

use std::cell::Cell;
use std::error::Error;
use std::time::Instant;

use tray_icon::menu::{CheckMenuItem, IsMenuItem, Menu, MenuItem, PredefinedMenuItem, Submenu};
use tray_icon::{Icon, TrayIcon, TrayIconBuilder};

use crate::i18n::Strings;
use crate::state::{AppState, SPANS, Span};

pub const ID_SYSTEM: &str = "system";
pub const ID_DISPLAY: &str = "display";
pub const ID_REMAIN: &str = "remain";
pub const ID_HOLD: &str = "hold";
pub const ID_QUIT: &str = "quit";

/// Duration entries use ids `span0`, `span1`, and so on, where the number is an
/// index into [`SPANS`]. A prefix plus an index avoids maintaining one constant
/// per duration: adding or removing options means touching only `SPANS`.
pub const ID_SPAN_PREFIX: &str = "span";

/// build.rs compiles assets/active.ico as resource id 1 and idle.ico as id 2.
const ICON_ACTIVE: u16 = 1;
const ICON_IDLE: u16 = 2;

pub struct Ui {
    tray: TrayIcon,
    strings: &'static Strings,
    system: CheckMenuItem,
    display: CheckMenuItem,
    /// The duration radio group. muda has no native radio item, so mutual
    /// exclusion is maintained by hand: each sync checks exactly the one that
    /// matches the current span.
    spans: Vec<(CheckMenuItem, Span)>,
    remaining: MenuItem,
    /// Shown only while a CLI process has announced a hold. It is inserted into
    /// and removed from the menu rather than left in place greyed out, so a
    /// menu with nothing to report has no dead row in it.
    hold: MenuItem,
    hold_shown: Cell<bool>,
    /// Where the hold row goes, measured from the menu that was actually built
    /// rather than hand counted. muda's insert is a `Vec::insert` underneath,
    /// which panics on an out of range position, and this process aborts on
    /// panic with no console to print to: the icon would simply vanish.
    hold_index: usize,
    icon_active: Icon,
    icon_idle: Icon,
    /// The menu has to stay alive, or right-clicking the tray pops up nothing.
    menu: Menu,
    _span_menu: Submenu,
}

impl Ui {
    pub fn build(strings: &'static Strings) -> Result<Ui, Box<dyn Error>> {
        let icon_active = Icon::from_resource(ICON_ACTIVE, None)?;
        let icon_idle = Icon::from_resource(ICON_IDLE, None)?;

        let system = CheckMenuItem::with_id(ID_SYSTEM, strings.keep_system, true, false, None);
        let display = CheckMenuItem::with_id(ID_DISPLAY, strings.keep_screen, true, false, None);

        // Duration entries are generated by zipping SPANS with the labels for
        // the active language; the index becomes the id suffix.
        let span_items: Vec<(CheckMenuItem, Span)> = SPANS
            .iter()
            .zip(strings.spans.iter())
            .enumerate()
            .map(|(i, (span, label))| {
                let item = CheckMenuItem::with_id(
                    format!("{ID_SPAN_PREFIX}{i}"),
                    label,
                    true,
                    *span == Span::Forever, // start out on "Indefinitely"
                    None,
                );
                (item, *span)
            })
            .collect();
        let span_refs: Vec<&dyn IsMenuItem> = span_items
            .iter()
            .map(|(item, _)| item as &dyn IsMenuItem)
            .collect();
        let span_menu = Submenu::with_items(strings.duration, true, &span_refs)?;

        // The "remaining" row is display only and never clickable, and so is
        // the CLI hold row.
        let remaining = MenuItem::with_id(ID_REMAIN, strings.no_timer, false, None);
        let hold = MenuItem::with_id(ID_HOLD, "", false, None);
        let quit = MenuItem::with_id(ID_QUIT, strings.exit, true, None);

        let menu = Menu::with_items(&[
            &system,
            &display,
            &PredefinedMenuItem::separator(),
            &span_menu,
            &PredefinedMenuItem::separator(),
            &remaining,
            &PredefinedMenuItem::separator(),
            &quit,
        ])?;

        // Last two entries are the separator and Exit, so inserting here puts
        // the hold row directly under "remaining" whatever the menu grows into.
        let hold_index = menu.items().len().saturating_sub(2);

        let tray = TrayIconBuilder::new()
            .with_menu(Box::new(menu.clone()))
            .with_icon(icon_idle.clone())
            .with_tooltip((strings.tooltip)(None, None, None))
            .with_menu_on_left_click(true)
            .build()?;

        Ok(Ui {
            tray,
            strings,
            system,
            display,
            spans: span_items,
            remaining,
            hold,
            hold_shown: Cell::new(false),
            hold_index,
            icon_active,
            icon_idle,
            menu,
            _span_menu: span_menu,
        })
    }

    /// Push the state onto the UI. This is the **only** path that updates the
    /// UI: every change to `AppState` must be followed by a call here, and no
    /// other code is allowed to touch menu items directly.
    ///
    /// `hold` is the label of a hold announced by a `caffeinate` CLI process,
    /// if any. It deliberately does not move the two checkmarks: those report
    /// what the user chose, and a CLI hold is somebody else's business. What it
    /// does change is the icon and the tooltip, which report the real effect.
    pub fn sync(&self, state: &AppState, now: Instant, power_ok: bool, hold: Option<&str>) {
        self.system.set_checked(state.system());
        self.display.set_checked(state.display());

        for (item, span) in &self.spans {
            item.set_checked(*span == state.span());
        }

        self.remaining
            .set_text(state.remaining_text(now, self.strings));

        self.sync_hold_row(hold);

        let held_by_user = state.is_active() && power_ok;
        let icon = if held_by_user || hold.is_some() {
            self.icon_active.clone()
        } else {
            self.icon_idle.clone()
        };
        let _ = self.tray.set_icon(Some(icon));

        // The tooltip is composed entirely inside i18n, including the CLI hold,
        // so the icon above and the text here can never disagree about whether
        // anything is being held.
        let tip = if power_ok {
            state.tooltip(now, self.strings, hold)
        } else {
            self.strings.tip_power_failed.to_string()
        };
        let _ = self.tray.set_tooltip(Some(tip));
    }

    /// Insert or remove the CLI hold row so the menu only carries it when there
    /// is something to say.
    fn sync_hold_row(&self, hold: Option<&str>) {
        match (hold, self.hold_shown.get()) {
            (Some(label), true) => self.hold.set_text((self.strings.cli_hold)(label)),
            (Some(label), false) => {
                self.hold.set_text((self.strings.cli_hold)(label));
                let _ = self.menu.insert(&self.hold, self.hold_index);
                self.hold_shown.set(true);
            }
            (None, true) => {
                // muda detaches the row before its own bookkeeping can fail, so
                // treating this as done regardless is the honest reading: the
                // row is gone either way, and pretending otherwise would leave
                // this stuck believing a detached item is still on screen.
                let _ = self.menu.remove(&self.hold);
                self.hold_shown.set(false);
            }
            (None, false) => {}
        }
    }
}
